package com.example.backend.mapper;

import com.example.backend.dto.ProjectMemberRequestDTO;
import com.example.backend.dto.ProjectMemberResponseDTO;
import com.example.backend.entity.Project;
import com.example.backend.entity.ProjectMember;
import com.example.backend.entity.User;
import com.example.backend.entity.enums.ProjectRole;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class ProjectMemberMapperTest {

    // Generated by MapStruct at compile time (target/generated-sources)
    private final ProjectMemberMapper mapper = new ProjectMemberMapperImpl();

    private ProjectMember buildEntity() {
        User user = new User();
        user.setId(1);
        user.setUsername("ruslan");

        Project project = new Project();
        project.setId(2);
        project.setName("Kanban Board");

        ProjectMember member = new ProjectMember();
        member.setId(10);
        member.setProjectRole(ProjectRole.MANAGER);
        member.setJoinedAt(LocalDateTime.of(2026, 9, 30, 12, 0));
        member.setUser(user);
        member.setProject(project);
        return member;
    }

    @Test
    void toDto_mapsAllFieldsIncludingNestedOnes() {
        ProjectMemberResponseDTO dto = mapper.toDto(buildEntity());

        assertEquals(10, dto.id());
        assertEquals(ProjectRole.MANAGER, dto.projectRole());
        assertEquals(LocalDateTime.of(2026, 9, 30, 12, 0), dto.joinedAt());
        assertEquals(1, dto.userId());
        assertEquals("ruslan", dto.username());
        assertEquals(2, dto.projectId());
        assertEquals("Kanban Board", dto.projectName());
    }

    @Test
    void toDto_returnsNullForNullEntity() {
        assertNull(mapper.toDto(null));
    }

    @Test
    void toDtoList_mapsEveryElement() {
        List<ProjectMemberResponseDTO> result =
                mapper.toDtoList(List.of(buildEntity(), buildEntity()));

        assertEquals(2, result.size());
        assertEquals("ruslan", result.get(0).username());
    }

    @Test
    void toEntity_mapsRoleAndLeavesRelationsAndGeneratedFieldsEmpty() {
        ProjectMemberRequestDTO request =
                new ProjectMemberRequestDTO(1, 2, ProjectRole.OWNER);

        ProjectMember entity = mapper.toEntity(request);

        assertEquals(ProjectRole.OWNER, entity.getProjectRole());
        assertNull(entity.getId());
        assertNull(entity.getJoinedAt());
        assertNull(entity.getUser());     // set later in the service
        assertNull(entity.getProject());  // set later in the service
    }

    @Test
    void updateEntity_changesRoleButKeepsIdentityAndRelations() {
        ProjectMember existing = buildEntity();
        ProjectMemberRequestDTO request =
                new ProjectMemberRequestDTO(99, 99, ProjectRole.MEMBER);

        mapper.updateEntity(request, existing);

        assertEquals(ProjectRole.MEMBER, existing.getProjectRole());
        assertEquals(10, existing.getId());
        assertEquals(1, existing.getUser().getId());
        assertEquals(2, existing.getProject().getId());
        assertNotNull(existing.getJoinedAt());
    }
}